### ISSUE TITLE
Translation using the proper way to do gettext

### ISSUE THREAD

**Issue by pawal** [zonemaster/zonemaster-engine#191]
Locale::TextDomain is used by the Engine to translate strings to another language. However, its use in the code does not make the gettext workflow to work at all. Strings used in the code should be done in a way so that language files can be generated from it. A typical way to use it is as such:

```
my $alt = $__{"Hello World!\n"};
```

$alt then contains the localized string. The function name can be changed.

See also this article: http://perladvent.org/2013/2013-12-09.html

**Comment by matsduf** [comment]
This requires thorough investigation.

**Comment by mattias-p** [comment]
Today there's a single `__` subroutine call in `Zonemaster::Translator` that performs all the translations. For the gettext work flow to work out, the `__` call needs to be distributed to each one of the MSGID string literals, which in turn means that the `Zonemaster::Test` interface needs to be extended with the possibility to perform translation with arguments.

Proposed API change:
 1. Add `Zonemaster::Test::translate_module_tag()` that takes a tag and translation arguments.
 2. Deprecate `Zonemaster::Test::translation()` to have it removed in a future breaking change.

Implied code changes:
 1. `translate_module_tag()` needs to be implemented in each standard test module and also in `Translator`.
 2. `Translator` needs a mechanism for mapping (upper case) module names to actual test modules.
 3. `Zonemaster::Translator::translate_tag()` needs to be updated to call `translate_module_tag()` (for the given test module) if it exists, instead of looking in `Zonemaster::Translator::data`.
 4. New tests need to be written for the new `translate_module_tag()` implementations.

Questions remain regarding `data` and the implementation of `translation()` during its deprecation period. I believe it is possible get the untranslated messages for `translation()` (and `Zonemaster::Translator::_system_translation()`) from `translate_module_tag()` and `Zonemaster::Test::metadata()` by temporarily setting locale "C" and not giving any translation arguments to `translate_module_tag()`.

If we can allow test modules implementing `translate_module_tag()` to drop their `translation()` method, we could simplify the standard test module implementations, making life easier for test module implementers. If we can stop populating `data` from test modules only implementing `translate_module_tag()`, we don't have to derive any untranslated messages at all.

**Comment by matsduf** [comment]
Will investigate.

**Comment by sandoche2k** [comment]
@matsduf @mattias-p, please indicate the conclusion of your investigation

**Comment by mattias-p** [comment]
A proper gettext workflow has been implemented.
