### ISSUE TITLE
Add documentation and Unit test for zonemaster/zonemaster-engine#487

### ISSUE THREAD

**Issue by vlevigneron** [zonemaster/zonemaster-engine#488]
Explain why we have a Hack and add unit tests for non regression on this hack.
See  zonemaster/zonemaster-backend#476 and  zonemaster/zonemaster-engine#487

**Comment by sandoche2k** [comment]
@vlevigneron to write some text explaining the issue

**Comment by matsduf** [comment]
@mvw-afnic, is this something you can look at in the context of broken name server program?

**Comment by mvw-afnic** [comment]
It seems that the issue that is being referred to here (that is, #476) is a bug within either Perl or Moose, where an attempt is made to convert a string such as “3,14” into a floating point number. This conversion fails because it should be “3.14” with a point instead of a comma. The name server that I’m developing won’t be of much help, I’m afraid.

**Comment by matsduf** [comment]
Could it be a locale issue? In many locale the decimal separator is ",", not ".".

**Comment by mvw-afnic** [comment]
Yes indeed I meant zonemaster/zonemaster-backend#476. And it looks like a locale issue to me as well.

I have found a more in-depth discussion of the Perl issue here: https://github.com/Perl/perl5/issues/13089
