### ISSUE TITLE
Proper English msgids

### ISSUE THREAD

**Issue by mattias-p** [zonemaster/zonemaster-engine#788]
All msgid strings should use proper English. Especially since the argument was made in #787 that all msgid strings should end with a dot. Current non-English msgids are:
* ASN_INFOS_RAW
* ASN_INFOS_ANNOUNCE_BY
* ASN_INFOS_ANNOUNCE_IN

**Comment by matsduf** [comment]
I think we could make a distinktion between msgid for INFO and higher, on one side, and DEBUG and lower, on the other. If a msgid is clearly for DEBUG or lower then it could make sense to have a more code like msgid. TEST_CASE_END and TEST_CASE_START are clear examples of that. You would only care about them for debugging.

**Comment by mattias-p** [comment]
I don't care much about the milestone, but I think it's wrong to require trailing dots for code-like messages. They shouldn't be treated like they're human language sentences.

**Comment by matsduf** [comment]
I really do not see the problem of terminating code-like messages with a dot, but they could also be without. The reason why I argue for terminating all msgid's (and actually all msgstr's too) with a dot are:
* Instruction will be simpler, both for code writer and translator.
* It will be fairly simple to write and maintain a tool that checks all msgid's and msgstr's for the dot.

I have no problem that the following messages are made into msgid's written in English with a terminating dot:
* ASN_INFOS_RAW
* ASN_INFOS_ANNOUNCE_BY
* ASN_INFOS_ANNOUNCE_IN

The remaining two (TEST_CASE_END and TEST_CASE_START) are different because they created to stick out as code to indicate the flow of tests. They are also special because they should preferably not be translated in a true sence. msgstr should be the same as msgid. If it helps to resolve the knot, I suggest that these two have no final dot, but as documented exceptions. When we create a tool to test msgid's and msgstr's it should make an expection for TEST_CASE_END and TEST_CASE_START.

**Comment by mattias-p** [comment]
I removed TEST_CASE_END and TEST_CASE_START from the issue description.

**Comment by matsduf** [comment]
Resolved by #795.
